export type Language = 'ja' | 'en'

export const LANGUAGE_OPTIONS: readonly { value: Language; label: string }[] = [
  { value: 'ja', label: '日本語' },
  { value: 'en', label: 'English' },
]

const LANGUAGE_KEY = 'screw-counter-language-v1'

function persistentStorage(): Storage | null {
  try { return window.localStorage } catch { return null }
}

export function detectLanguage(languages: readonly string[] = typeof navigator === 'undefined' ? [] : navigator.languages): Language {
  return languages.some((language) => language.toLowerCase().startsWith('ja')) ? 'ja' : 'en'
}

export function loadLanguage(): Language {
  try {
    const saved = persistentStorage()?.getItem(LANGUAGE_KEY)
    if (saved === 'ja' || saved === 'en') return saved
  } catch { /* Storage is optional. */ }
  return detectLanguage()
}

export function saveLanguage(language: Language): void {
  try { persistentStorage()?.setItem(LANGUAGE_KEY, language) } catch { /* Storage is optional. */ }
}

const messages = {
  ja: {
    appTitle: 'ねじカウンター生成器',
    appDescription: '印刷用STLと組立用STEPをこのブラウザ内で生成します。',
    relatedLinks: '関連リンク', language: '言語', settings: '設定', basic: '基本', showAdvanced: '詳細設定', hideAdvanced: '詳細設定を隠す', resetSettings: '既定値に戻す', importSettings: '設定を読み込む', downloadSettings: '設定ファイルをダウンロード', settingsImported: '設定を読み込みました。', settingsImportFailed: '設定ファイルを読み込めませんでした。', settingsReset: '設定を既定値に戻しました。', version: 'バージョン', commitDate: 'コミット日時', unknown: '不明',
    preview: 'プレビュー', printPlate: '印刷プレート', realtimePreview: 'リアルタイムプレビュー', returnAssembly: '組立プレビューに戻る', showPrintPreview: '印刷プレビューを表示', previewDisplayMode: 'プレビュー表示モード', resetPreviewDisplay: '表示をリセット', assembled: '完成', exploded: 'パーツ分離', twoDimensional: '2D', selectPrintPlate: '印刷プレートを選択', plate: 'プレート', parts: '部品', loading3d: '3Dプレビューを準備しています…',
    overallSize: '外形', pitch: 'ピッチ', capacity: '収容本数', pieces: '本', output: '出力', fixSettings: '設定を修正してください', generate: 'モデルを生成', generating: 'モデルを生成中…', cancelGeneration: '生成を中止',
    print3mf: 'Bambu Studio 用3MF', print3mfDescription: '5部品を選択したプレートへ印刷向きで配置します。Bambu Studioで機種・材料・印刷条件を選んでスライスしてください。組立時はスライダーをベースへ上から載せ、その後トレーを固定します。', plateSize: 'プレートサイズ', generate3mf: '3MFを生成してプレビュー', generating3mf: '3MFを生成中…', download3mf: '3MFをダウンロード', footer: 'プリセットのねじ寸法は規格保証値ではありません。実物を測定し、印刷条件と実機での動作を確認してください。',
    downloadFiles: '生成ファイルのダウンロード', downloadZip: 'ZIPで一括ダウンロード', notes: '確認事項', dataUsage: '通信量の確認', dataUsageQuestion: '現在の回線では通信量を抑える設定またはモバイル回線が検出されました。{label}を続けますか？', cancel: 'キャンセル', continue: '続ける',
    initialStatus: '設定を確認してから「モデルを生成」を選んでください。', loadingDefaultPreview: '事前生成プレビューを読み込んでいます…', realtimeOff: 'リアルタイムプレビューはオフです。', twoDimensionalUpdated: '2Dプレビューを更新しました。3Dは表示時に生成します。', applyingPreview: '設定の変更をプレビューに反映しています…', fixInputToPreview: '入力を修正するとプレビューを更新できます。', waitingRealtime: 'リアルタイムプレビューの生成を待機しています。', generatingPreview: 'プレビューを生成しています…', previewUpdated: 'プレビューを更新しました。', cannotGeneratePreview: 'プレビューを生成できませんでした。', waitingDefaultPreview: '事前生成プレビューの取得を待機しています。', showingDefaultPreview: '事前生成プレビューを表示しています。', cannotLoadDefaultPreview: '事前生成プレビューを読み込めませんでした。',
    downloadCadEngine: 'CADエンジンの取得', cadEngineDetail: '初回のみCADエンジン約23 MB（圧縮時約7.3 MB）を取得します。', downloadDefaultPreview: '事前生成プレビューの取得', defaultPreviewDetail: '初回のみ事前生成した3Dプレビュー約{compressed}（展開後約{raw}）を取得します。', preparingCad: 'CADエンジンを準備しています…', modelGenerated: 'モデルを生成しました。', generationCancelled: '生成を中止しました。設定を変更して再生成できます。', cannotGenerateModel: 'モデルを生成できませんでした。', generating3mfFile: '3MFファイルを生成しています…', generatingModelForPrint: '印刷用モデルを生成しています…', generated3mf: 'Bambu Studio用3MFを{count}プレートで生成しました。', plateDoesNotFit: '部品のいずれかが{plate}のプレートに収まりません。取り出し回数や本数を減らすか、大きいプレートを選んでください。', cannotGenerate3mf: '3MFファイルを生成できませんでした。',
    fieldLidStyle: 'ふたの形状', fieldLidStyleDescription: '切り欠き用は枠の切り欠きと上部の細い帯だけを覆い、手前2か所で固定します。', lidFull: '全面を覆う', lidCutout: '切り欠き部分だけを覆う',
    funnelDepth: '漏斗の深さ', funnel: '漏斗', funnelFile: '漏斗 STL', fieldFunnelAlignment: '漏斗の固定方法', fieldFunnelAlignmentDescription: '平らなベース裏面の四隅に浅く埋め込んだ磁石、または凹凸で取り付けます。磁石の突出分は漏斗側で受けます。凹凸の保持力は印刷条件に依存します。', fieldFunnelOutlet: '漏斗の出口幅', fieldFunnelOutletDescription: 'タブと反対側に寄せた正方形の出口幅です。高さ14 mmの箱形で、内部は出口へ傾斜します。ねじの流れやすさは印刷後に確認してください。',
    assemblyFile: '組立 STEP', baseFile: 'ベース STL', trayFile: 'トレー STL', sliderFile: 'スライダー STL', lidFile: 'ふた STL', dimensionsFile: '寸法・検証 JSON',
    dimensionsUnavailable: '設定が成立すると寸法プレビューを表示します。', topPreview: '本体外形 {length} × {width} mm の上面プレビュー', topPreviewNote: '穴の配置と本体外形を示す上面図です。', separation: '分離距離', noWebgl: 'このブラウザでは3Dプレビューを表示できません。ダウンロードしたSTLまたはSTEPをご利用ください。', printPlatePreview: '印刷プレート上の配置を回転・移動・ズームできる3Dプレビュー', modelPreview: 'クリックでパーツを表示・非表示にできる3Dプレビュー', partVisibility: '3Dパーツの表示切替', partColors: 'パーツの色', printPlateHelp: '{width} × {depth} mmプレート。', modelHelp: 'パーツ名またはモデルをクリックして表示・非表示を切り替えます。', viewerControls: 'ドラッグで回転、右ドラッグまたは2本指で移動、ホイールまたはピンチで拡大・縮小', base: 'ベース', tray: 'トレー', slider: 'スライダー', lid: 'ふた',
    categoryBasic: '基本', categoryBasicDescription: 'ねじの種類と一度に出す量', categoryOperation: '収納・操作', categoryOperationDescription: '容量と操作感', categoryScrewDimensions: 'ねじの実測値', categoryScrewDimensionsDescription: '実物に合わせる寸法', categoryMagnet: 'ふた・漏斗の固定寸法', categoryMagnetDescription: '磁石または凹凸の寸法', categoryClearance: 'クリアランス', categoryClearanceDescription: 'プリンターに合わせる余裕',
    fieldScrew: '対象のねじ', fieldScrewDescription: '選択すると頭径などをそのねじの初期値に戻します。実測値は下で上書きできます。', fieldRows: '1回に出す本数', fieldRowsDescription: '引く方向と直交する穴の数です。', fieldColumns: '取り出し回数', fieldColumnsDescription: '引き出して取り出せる回数です。', times: '回', fieldScrewSpaceHeight: 'ねじ収納スペースの高さ', fieldScrewSpaceHeightDescription: 'トレー上面から閉じたふたの内側までの高さです。', fieldJoint: '本体の接合方法', fieldJointDescription: 'ねじ留めは四隅に M2×5 を4本使います。', screws: 'ねじ留め', glue: '接着', fieldLidAlignment: 'ふたの位置合わせ', fieldLidAlignmentDescription: '磁石を使うか、ふた側の凸とトレー側の穴で合わせるかを選びます。', magnets: '磁石', pegs: '凹凸', fieldDetent: 'クリック感を付ける', fieldDetentDescription: '各停止位置でスライダーを保持します。', fieldDetentSpringWidth: 'ばね幅', fieldDetentSpringWidthDescription: 'クリック用の板ばねの幅です。', fieldDetentSpringLength: 'ばね長さ', fieldDetentSpringLengthDescription: '短くするとクリック用の板ばねが硬くなります。', fieldDetentDiameter: 'クリックの凹凸径', fieldDetentDiameterDescription: 'スライダーの凸径です。ベース側の凹径は0.2 mm大きく作ります。', fieldHeadDiameter: 'ねじ頭径', fieldHeadDiameterDescription: '選んだねじの初期値です。実測値で上書きできます。', fieldShaftDiameter: 'ねじ軸径', fieldShaftDiameterDescription: '選んだねじの初期値です。実測値で上書きできます。', fieldSlotWidth: 'スロット幅', fieldSlotWidthDescription: '選んだねじの初期値です。実測値で上書きできます。', fieldPitch: 'ピッチ', fieldPitchDescription: '自動計算値です。変更すると上書きできます。', fieldMagnetDiameter: '磁石 / 凹凸の基準径', fieldMagnetDiameterDescription: '磁石の実測直径、または凹凸モードの受け穴の基準直径です。', fieldMagnetThickness: '磁石の厚み / 受け穴の深さ', fieldMagnetThicknessDescription: '磁石の実測厚み、または凹凸モードの受け穴の基準深さです。', fieldSlideClearance: 'スライドのクリアランス', fieldSlideClearanceDescription: 'スライダーの片側と上下に確保する余裕です。', fieldTrayHoleClearance: 'ベース角穴の幅クリアランス', fieldTrayHoleClearanceDescription: 'ねじ頭径に加える、ベース下面の四角い出口の一辺の余裕です。小さくすると穴が狭くなります。', fieldMagnetDiameterClearance: '位置合わせ穴の径クリアランス', fieldMagnetDiameterClearanceDescription: '磁石または凹凸の基準径に加える余裕です。', fieldMagnetDepthClearance: '位置合わせ穴の深さクリアランス', fieldMagnetDepthClearanceDescription: '磁石の厚みまたは凹凸の基準深さに加える余裕です。',
  },
  en: {
    appTitle: 'Screw Counter Builder',
    appDescription: 'Generate print-ready STL files and an assembly STEP file entirely in your browser.',
    relatedLinks: 'Related links', language: 'Language', settings: 'Settings', basic: 'Basic', showAdvanced: 'Advanced settings', hideAdvanced: 'Hide advanced settings', resetSettings: 'Reset to defaults', importSettings: 'Import settings', downloadSettings: 'Download settings file', settingsImported: 'Settings imported.', settingsImportFailed: 'Could not import the settings file.', settingsReset: 'Settings were reset to defaults.', version: 'Version', commitDate: 'Commit date', unknown: 'Unknown',
    preview: 'Preview', printPlate: 'Print plate', realtimePreview: 'Live preview', returnAssembly: 'Return to assembly preview', showPrintPreview: 'Show print preview', previewDisplayMode: 'Preview display mode', resetPreviewDisplay: 'Reset view', assembled: 'Assembled', exploded: 'Exploded', twoDimensional: '2D', selectPrintPlate: 'Select print plate', plate: 'Plate', parts: 'parts', loading3d: 'Preparing 3D preview…',
    overallSize: 'Overall size', pitch: 'Pitch', capacity: 'Capacity', pieces: 'pieces', output: 'Output', fixSettings: 'Fix the settings below', generate: 'Generate model', generating: 'Generating model…', cancelGeneration: 'Cancel generation',
    print3mf: 'Bambu Studio 3MF', print3mfDescription: 'Places all five parts in print orientation on the selected plate. Choose your printer, material, and print settings in Bambu Studio before slicing. For assembly, place the slider into the base from above, then secure the tray.', plateSize: 'Plate size', generate3mf: 'Generate and preview 3MF', generating3mf: 'Generating 3MF…', download3mf: 'Download 3MF', footer: 'The preset screw dimensions are not guaranteed standard values. Measure the actual screw and confirm operation with your print settings and a physical test.',
    downloadFiles: 'Download generated files', downloadZip: 'Download all as ZIP', notes: 'Notes', dataUsage: 'Data usage check', dataUsageQuestion: 'A data-saving setting or mobile connection was detected. Continue downloading {label}?', cancel: 'Cancel', continue: 'Continue',
    initialStatus: 'Review the settings, then select “Generate model”.', loadingDefaultPreview: 'Loading the pre-generated preview…', realtimeOff: 'Live preview is off.', twoDimensionalUpdated: 'Updated the 2D preview. The 3D view is generated when shown.', applyingPreview: 'Applying your settings to the preview…', fixInputToPreview: 'Fix the inputs to update the preview.', waitingRealtime: 'Waiting to generate the live preview.', generatingPreview: 'Generating preview…', previewUpdated: 'Preview updated.', cannotGeneratePreview: 'Could not generate the preview.', waitingDefaultPreview: 'Waiting to download the pre-generated preview.', showingDefaultPreview: 'Showing the pre-generated preview.', cannotLoadDefaultPreview: 'Could not load the pre-generated preview.',
    downloadCadEngine: 'Download CAD engine', cadEngineDetail: 'This first download gets the CAD engine: about 23 MB, or about 7.3 MB compressed.', downloadDefaultPreview: 'Download pre-generated preview', defaultPreviewDetail: 'This first download gets a pre-generated 3D preview: about {compressed} compressed, or {raw} after decompression.', preparingCad: 'Preparing CAD engine…', modelGenerated: 'Model generated.', generationCancelled: 'Generation cancelled. Change the settings and generate again.', cannotGenerateModel: 'Could not generate the model.', generating3mfFile: 'Generating 3MF file…', generatingModelForPrint: 'Generating model for printing…', generated3mf: 'Generated a Bambu Studio 3MF on {count} plate(s).', plateDoesNotFit: 'A part does not fit on the {plate} plate. Reduce the number of pieces or columns, or select a larger plate.', cannotGenerate3mf: 'Could not generate the 3MF file.',
    fieldLidStyle: 'Lid coverage', fieldLidStyleDescription: 'The cutout lid covers the frame cutout and a narrow top strip, using only the two front mounts.', lidFull: 'Full cover', lidCutout: 'Cutout cover',
    funnelDepth: 'Funnel depth', funnel: 'Funnel', funnelFile: 'Funnel STL', fieldFunnelAlignment: 'Funnel attachment', fieldFunnelAlignmentDescription: 'Attach with shallow magnet pockets or pegs at the four corners of the flat base underside. The funnel receives the projecting magnets. Peg retention depends on print fit.', fieldFunnelOutlet: 'Funnel outlet width', fieldFunnelOutletDescription: 'Width of the square outlet offset away from the tab. The 14 mm tall box slopes internally toward the outlet. Test screw flow after printing.',
    assemblyFile: 'Assembly STEP', baseFile: 'Base STL', trayFile: 'Tray STL', sliderFile: 'Slider STL', lidFile: 'Lid STL', dimensionsFile: 'Dimensions & validation JSON',
    dimensionsUnavailable: 'A dimension preview appears when the settings are valid.', topPreview: 'Top preview of the {length} × {width} mm body', topPreviewNote: 'Top view showing the hole layout and body outline.', separation: 'Separation', noWebgl: 'This browser cannot display the 3D preview. Use the downloaded STL or STEP files instead.', printPlatePreview: '3D preview of the print-plate layout; rotate, pan, and zoom', modelPreview: '3D preview; click a part to show or hide it', partVisibility: '3D part visibility', partColors: 'Part colors', printPlateHelp: '{width} × {depth} mm plate.', modelHelp: 'Click a part name or the model to show or hide it.', viewerControls: 'Drag to rotate. Right-drag or two fingers to pan. Use the wheel or pinch to zoom.', base: 'Base', tray: 'Tray', slider: 'Slider', lid: 'Lid',
    categoryBasic: 'Basic', categoryBasicDescription: 'Screw type and batch size', categoryOperation: 'Storage & operation', categoryOperationDescription: 'Capacity and operation feel', categoryScrewDimensions: 'Measured screw dimensions', categoryScrewDimensionsDescription: 'Dimensions matched to the actual screw', categoryMagnet: 'Lid & funnel attachment', categoryMagnetDescription: 'Magnet or peg dimensions', categoryClearance: 'Clearance', categoryClearanceDescription: 'Allowances matched to your printer',
    fieldScrew: 'Target screw', fieldScrewDescription: 'Selecting a screw resets its head diameter and related values to the preset. You can override them below.', fieldRows: 'Pieces per batch', fieldRowsDescription: 'Number of holes perpendicular to the pull direction.', fieldColumns: 'Number of batches', fieldColumnsDescription: 'Number of batches available by pulling the slider.', times: 'batches', fieldScrewSpaceHeight: 'Screw storage height', fieldScrewSpaceHeightDescription: 'Height from the tray top to the inside of the closed lid.', fieldJoint: 'Body joint', fieldJointDescription: 'The screw joint uses four M2×5 screws at the corners.', screws: 'Screws', glue: 'Glue', fieldLidAlignment: 'Lid alignment', fieldLidAlignmentDescription: 'Choose magnets or lid pegs with matching tray holes.', magnets: 'Magnets', pegs: 'Pegs', fieldDetent: 'Add click stops', fieldDetentDescription: 'Holds the slider at each stop position.', fieldDetentSpringWidth: 'Spring width', fieldDetentSpringWidthDescription: 'Width of the leaf spring used for click stops.', fieldDetentSpringLength: 'Spring length', fieldDetentSpringLengthDescription: 'A shorter leaf spring makes the click stop stiffer.', fieldDetentDiameter: 'Click-stop diameter', fieldDetentDiameterDescription: 'Diameter of the slider bump. The base recess is 0.2 mm larger.', fieldHeadDiameter: 'Screw head diameter', fieldHeadDiameterDescription: 'Preset for the selected screw. Override it with a measurement.', fieldShaftDiameter: 'Screw shaft diameter', fieldShaftDiameterDescription: 'Preset for the selected screw. Override it with a measurement.', fieldSlotWidth: 'Slot width', fieldSlotWidthDescription: 'Preset for the selected screw. Override it with a measurement.', fieldPitch: 'Pitch', fieldPitchDescription: 'Calculated automatically. Changing it overrides the value.', fieldMagnetDiameter: 'Magnet / peg reference diameter', fieldMagnetDiameterDescription: 'Measured magnet diameter, or the reference diameter for the peg-mode receiving hole.', fieldMagnetThickness: 'Magnet thickness / hole depth', fieldMagnetThicknessDescription: 'Measured magnet thickness, or the reference depth for the peg-mode receiving hole.', fieldSlideClearance: 'Slider clearance', fieldSlideClearanceDescription: 'Allowance on each side and above/below the slider.', fieldTrayHoleClearance: 'Square base-hole width clearance', fieldTrayHoleClearanceDescription: 'Allowance added to the screw head diameter to set the side length of each square outlet in the base floor. A smaller value makes the hole narrower.', fieldMagnetDiameterClearance: 'Alignment-hole diameter clearance', fieldMagnetDiameterClearanceDescription: 'Allowance added to the magnet or peg reference diameter.', fieldMagnetDepthClearance: 'Alignment-hole depth clearance', fieldMagnetDepthClearanceDescription: 'Allowance added to the magnet thickness or peg reference depth.',
  },
} as const

export type MessageKey = keyof typeof messages.ja

export function text(language: Language, key: MessageKey, values: Record<string, string | number> = {}): string {
  return messages[language][key].replace(/\{(\w+)\}/g, (_, name: string) => String(values[name] ?? `{${name}}`))
}

export function formatNumber(language: Language, value: number, options: Intl.NumberFormatOptions = { maximumFractionDigits: 1 }): string {
  return new Intl.NumberFormat(language === 'ja' ? 'ja-JP' : 'en-US', options).format(value)
}

export function localizeProgress(language: Language, message?: string): string | undefined {
  if (!message) return undefined
  const keys: Record<string, MessageKey> = {
    'Loading the CAD engine…': 'preparingCad', 'Building parts…': 'generating', 'Built base': 'base', 'Built tray': 'tray', 'Built slider': 'slider', 'Built lid': 'lid', 'Built funnel': 'funnel', 'Preparing export metadata…': 'generating', 'Exports are ready.': 'modelGenerated',
  }
  return keys[message] ? text(language, keys[message]) : message
}

export function localizeValidation(language: Language, message: string): string {
  const ja: Record<string, string> = {
    'Screw joints need magnet or peg diameter at least 5 mm for screw access': 'ねじを組み立てる通路を確保するため、ねじ留め時の磁石・凹凸径は5 mm以上にしてください。',
    'Funnel outlet needs at least head + 1 mm': '漏斗の出口幅をねじ頭径より1 mm以上大きくしてください。',
    'funnelAlignment must be magnets or pegs': '漏斗の固定方法を選び直してください。',
    'funnelOutlet must be 10..24 mm': '漏斗の出口幅は10〜24 mmにしてください。',
    'lidStyle must be full or cutout': 'ふたの形状を選び直してください。',
    'baseHoleClearance must be 0.1..1.2 mm': 'ベース穴の幅クリアランスは0.1〜1.2 mmにしてください。',
    'rows and columns must be positive integers within 12 × 24': '1回に出す本数は1〜12本、取り出し回数は1〜24回の整数にしてください。', 'screw must be M1.5, M2 or M3': '対象のねじはM1.5、M2、M3から選んでください。', 'joint must be screws or glue': '接合方法を選び直してください。', 'lidAlignment must be magnets or pegs': 'ふたの位置合わせ方法を選び直してください。', 'Supported magnet diameter is 3..8 mm': '磁石の直径は3〜8 mmにしてください。', 'Supported magnet thickness is 1..3 mm': '磁石の厚みは1〜3 mmにしてください。', 'slideClearance must be 0.15..0.6 mm': 'スライドのクリアランスは0.15〜0.6 mmにしてください。', 'trayHoleClearance must be 0.1..1.2 mm': 'トレー穴の径クリアランスは0.1〜1.2 mmにしてください。', 'screwSpaceHeight must be 3.5..30 mm': 'ねじ収納スペースの高さは3.5〜30 mmにしてください。', 'Magnet clearance is outside the supported range': '磁石穴のクリアランスが対応範囲を外れています。', 'detentSpringWidth must be 1.0..1.5 mm': 'ばね幅は1.0〜1.5 mmにしてください。', 'detentSpringLength must be 6..18 mm': 'ばね長さは6〜18 mmにしてください。', 'detentDiameter must be 2.0..3.2 mm': 'クリックの凹凸径は2.0〜3.2 mmにしてください。', 'Need shaft + 0.3 <= slot <= head - 0.6; measure the actual screw': '軸径 + 0.3 mm ≤ スロット幅 ≤ 頭径 − 0.6 mm となるよう、実物のねじを測ってください。', 'All numeric settings must be finite numbers': '数値欄には有限の値を入力してください。', 'Pitch needs >= window + 1.8 mm for separated batches': 'ピッチをねじ頭の窓幅より1.8 mm以上大きくしてください。', 'Need at least 0.5 mm between the corner screw and magnet pocket; increase screw space height or use a thinner magnet': '四隅のねじと磁石穴の間隔を0.5 mm以上にしてください。ねじ収納スペースの高さを増やすか、薄い磁石を選んでください。',
  }
  if (language === 'ja') return ja[message] ?? message
  const en: Record<string, string> = {
    'Screw joints need magnet or peg diameter at least 5 mm for screw access': 'Use a magnet or peg diameter of at least 5 mm with screw joints to allow assembly screw access.',
    'Funnel outlet needs at least head + 1 mm': 'Set the funnel outlet at least 1 mm wider than the screw head.',
    'funnelAlignment must be magnets or pegs': 'Choose a funnel attachment method.',
    'funnelOutlet must be 10..24 mm': 'Funnel outlet width must be from 10 to 24 mm.',
    'lidStyle must be full or cutout': 'Choose a lid coverage option.',
    'baseHoleClearance must be 0.1..1.2 mm': 'Base-hole width clearance must be from 0.1 to 1.2 mm.',
    'rows and columns must be positive integers within 12 × 24': 'Pieces per batch must be an integer from 1 to 12, and the number of batches must be an integer from 1 to 24.', 'screw must be M1.5, M2 or M3': 'Choose M1.5, M2, or M3 as the target screw.', 'joint must be screws or glue': 'Choose a body joint method.', 'lidAlignment must be magnets or pegs': 'Choose a lid alignment method.', 'Supported magnet diameter is 3..8 mm': 'Magnet diameter must be from 3 to 8 mm.', 'Supported magnet thickness is 1..3 mm': 'Magnet thickness must be from 1 to 3 mm.', 'slideClearance must be 0.15..0.6 mm': 'Slider clearance must be from 0.15 to 0.6 mm.', 'trayHoleClearance must be 0.1..1.2 mm': 'Tray-hole diameter clearance must be from 0.1 to 1.2 mm.', 'screwSpaceHeight must be 3.5..30 mm': 'Screw storage height must be from 3.5 to 30 mm.', 'Magnet clearance is outside the supported range': 'Magnet-hole clearance is outside the supported range.', 'detentSpringWidth must be 1.0..1.5 mm': 'Spring width must be from 1.0 to 1.5 mm.', 'detentSpringLength must be 6..18 mm': 'Spring length must be from 6 to 18 mm.', 'detentDiameter must be 2.0..3.2 mm': 'Click-stop diameter must be from 2.0 to 3.2 mm.', 'Need shaft + 0.3 <= slot <= head - 0.6; measure the actual screw': 'Use a slot width between shaft + 0.3 mm and head − 0.6 mm; measure the actual screw.', 'All numeric settings must be finite numbers': 'Every numeric setting must be a finite number.', 'Pitch needs >= window + 1.8 mm for separated batches': 'Set the pitch at least 1.8 mm wider than the screw-head window.', 'Need at least 0.5 mm between the corner screw and magnet pocket; increase screw space height or use a thinner magnet': 'Keep at least 0.5 mm between the corner screw and magnet pocket. Increase storage height or use a thinner magnet.',
  }
  return en[message] ?? message
}
